language: python
python:
  - "3.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository ppa:pyside/ppa -y
  - sudo apt-get install -y python-pyside python3-pyqt4
install:
  - pip install tox
script: tox -e py33-pyside,py33-pyqt4
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
