language: python
python:
  - "3.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo add-apt-repository ppa:pyside/ppa -y
  - sudo apt-get install libqt4-dev libqt5-dev
  - sudo apt-get install -y python-pyside python-qt4 python-pyqt5
install:
  - pip install tox
script: tox
cache:
  directories:
    - /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages
