language: python
python:
  - "3.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - pip install --find-links wheelhouse/ pyside
  - python `which pyside_postinstall.py` -install
script:
  #- py.test --qtimpl PyQt4
  #- py.test --qtimpl PyQt5
  - py.test --qtimpl PySide
