language: python
python:
  - "3.4"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo apt-get install -y python3-pyqt4
  - sudo /usr/bin/pip3 install wheelhouse/PySide-1.2.2-cp34-cp34m-linux_x86_64.whl
  - sudo /usr/bin/python3 `which pyside_postinstall.py` -install
install:
  - pip install tox
script: tox -e py34-pyside
